services:
  db:
    image: postgres:16-alpine
    container_name: postgres_prestamos
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_prestamos_data:/var/lib/postgresql/data

volumes:
  postgres_prestamos_data:
    name: postgres_prestamos_data